apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  containers:
    - name: mariadb
      image: image-registry.openshift-image-registry.svc:5000/openshift/mariadb:latest
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_USER
        value: user
      - name: MYSQL_PASSWORD
        value: mypassword
      - name: MYSQL_DATABASE
        value: mydb
